apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  serviceName: redis-master
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: redis
          containerPort: 6379
        - name: redisinsight
          containerPort: 8001
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
        - configMapRef:
            name: redis-config
        {{- if .Values.auth.enabled }}
        - secretRef:
            name: redis-secret
        {{- end }}
        env:
        - name: REDIS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: REDIS_NAMESPACE
          value: {{ .Values.namespace }}
        volumeMounts:
        - name: data
          mountPath: /data
      - name: redis-insight
        image: redis/redisinsight:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: insight
          containerPort: 5540
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: insight-data
          mountPath: /data
      volumes:
      - name: insight-data
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
